kind: pipeline
type: docker
name: default

platform:
  os: linux
  arch: arm64
#trigger:
 # branch: 
  #  - master
  #event: 
   # - push  
steps:
  - name: clone
    image: alpine/git
    commands:
      - git clone https://ku.hudiej.com/gonebadei/test.git
      - cd test
      - echo "git 来了"

  - name: build
    image: golang
    commands:
      - go mod .
      - go build -o test
      - go test
      - echo "走到这个地方了"
      - pwd
  
  - name: docker
    image: plugins/docker
    settings:
      repo: registry.cn-beijing.aliyuncs.com/18392643987@163.com/test
      tags: 
        - ${DRONE_COMMIT_SHA:0:8}
        - latest
      dockerfile: Dockerfile
      username: 
        from_secret: 18392643987@163.com
      password:
        from_secret: Zc994606871
  #- name: docker
  #  image: docker
  #  commands:
  #    - docker login --username=<your_aliyun_username> --password=<your_aliyun_password> <your_aliyun_registry>
  #    - docker build -t <your_aliyun_registry>/<your_username>/<your_image>:${DRONE_COMMIT_SHA:0:8} .
  #    - docker push <your_aliyun_registry>/<your_username>/<your_image>:${DRONE_COMMIT_SHA:0:8}
  #  environment:
  #    your_aliyun_username:
  #      from_secret: aliyun_username
  #    your_aliyun_password:
  #      from_secret: aliyun_password

services:
  - name: docker
    image: tianon/docker
    volumes:
      - name: dockersock
        path: /var/run  

volumes:
  - name: dockersock
    host:
      path: /var/run


