kind: pipeline
type: docker
name: default

platform:
  os: linux
  arch: arm64
#trigger:
 # branch: 
  #  - master
  #event: 
   # - push  
steps:
  - name: clone
    image: alpine/git
    commands:
      - git clone https://ku.hudiej.com/gonebadei/test.git
      - cd test
      - echo "git 来了"