kind: pipeline
type: docker
name: build-multiarch-images

platform: 
  os: linux
  arch: arm64

steps: 
  - name: test
    image: golang
    commands: 
      - echo "hahah"
  - name: build-go-1
    image: golang
    commands: 
      - echo -n ${docker_username}
      - echo -n ${docker_password} | sha256sum
      - ls
      - go mod download
      - go build -o test
      - echo "又来到了查看目录的地方了"
      - ls
      - echo "走到这个地方了"
      - pwd
      - echo ${DRONE_COMMIT_SHA:0:8}
  - name: docker-buildx
    image: thegeeklab/drone-docker-buildx
    privileged: true
    settings: 
      registry: registry.cn-beijing.aliyuncs.com
      username: 18392643987@163.com
      password: Zc994606871
      repo: registry.cn-beijing.aliyuncs.com/huanmengerkong/test
      dockerfile: ./Dockerfile
      tags: 
        - latest
        - 0.0.6
      platforms: 
        - linux/arm64
        - linux/amd64

trigger: 
  branch: 
    - master

