kind: pipeline
name: default

platform: 
  os: linux
  arch: arm64
services: 
  - name: docker
    image: docker:dind
    privileged: true
    volumes: 
      - name: dockersock
        path: /var/run
steps: 
  - name: test
    image: golang
    environment: 
      DOCKER_USERNAME: 
        from_secret: docker_username
      DOCKER_PASSWORD: 
        from_secret: docker_password
    commands: 
      - echo "hahah" 
      - echo -n $DOCKER_USERNAME
      - echo -n $DOCKER_PASSWORD
  - name: build-go-1
    image: golang
    commands: 
      - echo -n ${docker_username}
      - echo -n ${docker_password} | sha256sum
      - ls
      - go mod download
      - go build -o test
      - echo "又来到了查看目录的地方了"
      - ls
      - echo "走到这个地方了"
      - pwd
      - echo ${DRONE_COMMIT_SHA:0:8}
  - name: prepare tag
    image: alpine
    commands: 
      - echo ${DRONE_COMMIT_SHA:0:8}
      - export SHORT_SHA=$(echo ${DRONE_COMMIT_SHA} | cut -c 1-8)
      - echo ${SHORT_SHA}
  - name: build_and_push
    image: docker
    environment: 
      fDOCKER_HOST: unix:///var/run/docker.sock  # 通过这种方式连接到 Docker service
      DOCKER_USERNAME: 
        from_secret: docker_username
      DOCKER_PASSWORD: 
        from_secret: docker_passwordf
    commands: 
      - docker  info
      - echo ${DOCKER_PASSWORD} | docker login --username=18392643987@163.com registry.cn-beijing.aliyuncs.com -p Zc994606871
      - docker  build -t registry.cn-beijing.aliyuncs.com/huanmengerkong/test:${DRONE_COMMIT_SHA:0:8} -f Dockerfile .
      - docker  images
      - docker  push registry.cn-beijing.aliyuncs.com/huanmengerkong/test:${DRONE_COMMIT_SHA:0:8}

volumes: 
  - name: dockersock
    temp: {}