kind: pipeline
name: default

platform:
  os: linux
  arch: arm64
    
steps:
- name: test
  image: golang
  environment:
    DOCKER_USERNAME:
        from_secret: docker_username
    DOCKER_PASSWORD:
        from_secret: docker_password
  commands:
      - echo "hahah" 
      - echo -n $DOCKER_USERNAME
      - echo -n $DOCKER_PASSWORD
- name: build-go-1
  image: golang
  commands:
     - echo -n ${docker_username} | sha256sum
     - echo -n ${docker_password} | sha256sum
     - ls
     - go mod download
     - go build -o test
     - go test
     - echo "走到这个地方了"
     - pwd