kind: pipeline
name: default

platform: 
  os: linux
  arch: arm64

steps: 
  - name: test
    image: golang
    environment: 
      DOCKER_USERNAME: 
        from_secret: docker_username
      DOCKER_PASSWORD: 
        from_secret: docker_password
    commands: 
      - echo "hahah" 
      - echo -n $DOCKER_USERNAME
      - echo -n $DOCKER_PASSWORD
  - name: build-go-1
    image: golang
    commands: 
      - echo -n ${docker_username}
      - echo -n ${docker_password} | sha256sum
      - ls
      - go mod download
      - go build -o test
      - echo "又来到了查看目录的地方了"
      - ls
      - echo "走到这个地方了"
      - pwd
      - echo ${DRONE_COMMIT_SHA:0:8}
  - name: prepare tag
    image: alpine
    commands: 
      - echo ${DRONE_COMMIT_SHA}
      - export SHORT_SHA=$(echo ${DRONE_COMMIT_SHA} | cut -c 1-8)
      - echo ${SHORT_SHA}

  - name: docker-push-server-1
    image: plugins/docker
    settings: 
      repo: registry.cn-beijing.aliyuncs.com/huanmengerkong/test
      tags: 
        - ${DRONE_COMMIT_SHA:0:8}
        - latest
      dockerfile: Dockerfile
      username: 18392643987@163.com
      password: Zc994606871