kind: pipeline
type: docker
name: default

platform: 
  os: linux
  arch: arm64
steps: 
  - name: build-go-1
    image: golang
    commands: 
      - echo -n ${docker_username}
      - echo -n ${docker_password} | sha256sum
      - ls
      - go mod download
      - go build -o test
      - echo "又来到了查看目录的地方了"
      - ls
      - echo "走到这个地方了"
      - pwd
      - echo ${DRONE_COMMIT_SHA:0:8}
  - name: prepare tag
    image: alpine
    commands: 
      - echo ${DRONE_COMMIT_SHA:0:8}
      - export SHORT_SHA=$(echo ${DRONE_COMMIT_SHA} | cut -c 1-8)
      - echo ${SHORT_SHA}
  - name: build_and_push
    image: plugins/docker
    volumes: 
      - name: docker-sock
        path: /var/run/docker.sock     #映射宿主机Docker
    commands: 
      - docker info
      - docker login --username=18392643987@163.com registry.cn-beijing.aliyuncs.com -p Zc994606871
      - docker  build -t registry.cn-beijing.aliyuncs.com/huanmengerkong/test:${DRONE_COMMIT_SHA:0:8} -f ./Dockerfile
      - docker  images
      - docker  push registry.cn-beijing.aliyuncs.com/huanmengerkong/test:${DRONE_COMMIT_SHA:0:8}

volumes: 
  - name: docker-sock
    host: 
      path: /var/run/docker.sock
